name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features


  build-and-push:
    runs-on: ubuntu-latest
    needs: clippy_check
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/diskwatcher:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/diskwatcher:latest
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Pull latest image
        run: docker pull ghcr.io/${{ github.repository_owner }}/diskwatcher:${{ github.sha }}

      - name: Stop and remove old container
        run: docker rm -f diskwatcher || true

      - name: Run new container
        run: |
          docker run -d \
            --name diskwatcher \
            --privileged \
            --network br0 \
            --ip 192.168.0.8 \
            -p 9101:9101 \
            -e TZ=America/New_York \
            -v /etc/localtime:/etc/localtime:ro \
            -v /dev:/dev \
            -v /var/local/emhttp:/var/local/emhttp:ro \
            ghcr.io/${{ github.repository_owner }}/diskwatcher:${{ github.sha }}
